### ISSUE TITLE
How to get `input` data from Scheduled event?

### ISSUE THREAD

**Issue by PatilShreyas** [aws/aws-lambda-java-libs#222]
How to get input data (JSON) from [Scheduled event](https://github.com/aws/aws-lambda-java-libs/blob/c491aa244ce5204bee290d5a0a345b2dcc96319d/aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/ScheduledEvent.java)?

For e.g. I've scheduled event in serverless.yml as below

```yml
      - schedule:
          rate: cron(0/15 * * * ? *)
          enabled: true
          input:
            testInput: "testInput"
```

How can I access this `testInput`?
